//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSActionSheetPlugin\src\main\java\com\ashera\actionsheet\ActionSheetPlugin.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "ActionSheetPlugin.h"
#include "FontDescriptor.h"
#include "FragmentRegistry.h"
#include "IConverter.h"
#include "IFragment.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "PluginInvoker.h"
#include "java/lang/Boolean.h"
#include "java/lang/Character.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"

#include "IBActionSheet.h"


@class NSString;


#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASActionSheetPlugin () {
 @public
  NSString *parentFragmentId_;
  id uiActionSheet_;
}

- (void)nativeSetTitleTextColorWithId:(id)titleTextColor;

- (void)nativeSetTitleBackgroundColorWithId:(id)bgColor;

- (void)nativeSetTitleTextSizeWithFloat:(float)value;

- (void)nativeSetTitleFontFamilyWithNSString:(NSString *)fontName
                                   withFloat:(float)textSize;

- (ASFontDescriptor *)getFontFamilyDescriptorWithNSString:(NSString *)fontName;

- (id)getTextSizeWithInt:(int32_t)textSize;

- (id)getTextColorWithNSString:(NSString *)color;

- (void)nativeSetCancelTextColorWithId:(id)cancelTextColor;

- (void)nativeSetCancelBackgroundColorWithId:(id)bgColor;

- (void)nativeSetCancelHighlightColorWithId:(id)bgColor;

- (void)nativeSetCancelTextSizeWithFloat:(float)value;

- (void)nativeSetCancelFontFamilyWithNSString:(NSString *)fontName
                                    withFloat:(float)textSize;

- (void)nativeSetDestructiveTextColorWithId:(id)destructiveTextColor;

- (void)nativeSetDestructiveBackgroundColorWithId:(id)bgColor;

- (void)nativeSetDestructiveHighlightColorWithId:(id)bgColor;

- (void)nativeSetDestructiveTextSizeWithFloat:(float)value;

- (void)nativeSetDestructiveFontFamilyWithNSString:(NSString *)fontName
                                         withFloat:(float)textSize;

- (void)nativeSetOtherTextColorWithId:(id)otherTextColor;

- (void)nativeSetOtherBackgroundColorWithId:(id)bgColor;

- (void)nativeSetOtherHighlightColorWithId:(id)bgColor;

- (void)nativeSetOtherTextSizeWithFloat:(float)value;

- (void)nativeSetOtherFontFamilyWithNSString:(NSString *)fontName
                                   withFloat:(float)textSize;

@end

J2OBJC_FIELD_SETTER(ASActionSheetPlugin, parentFragmentId_, NSString *)
J2OBJC_FIELD_SETTER(ASActionSheetPlugin, uiActionSheet_, id)

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetTitleTextColorWithId_(ASActionSheetPlugin *self, id titleTextColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetTitleBackgroundColorWithId_(ASActionSheetPlugin *self, id bgColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetTitleTextSizeWithFloat_(ASActionSheetPlugin *self, float value);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetTitleFontFamilyWithNSString_withFloat_(ASActionSheetPlugin *self, NSString *fontName, float textSize);

__attribute__((unused)) static ASFontDescriptor *ASActionSheetPlugin_getFontFamilyDescriptorWithNSString_(ASActionSheetPlugin *self, NSString *fontName);

__attribute__((unused)) static id ASActionSheetPlugin_getTextSizeWithInt_(ASActionSheetPlugin *self, int32_t textSize);

__attribute__((unused)) static id ASActionSheetPlugin_getTextColorWithNSString_(ASActionSheetPlugin *self, NSString *color);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetCancelTextColorWithId_(ASActionSheetPlugin *self, id cancelTextColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetCancelBackgroundColorWithId_(ASActionSheetPlugin *self, id bgColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetCancelHighlightColorWithId_(ASActionSheetPlugin *self, id bgColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetCancelTextSizeWithFloat_(ASActionSheetPlugin *self, float value);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetCancelFontFamilyWithNSString_withFloat_(ASActionSheetPlugin *self, NSString *fontName, float textSize);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetDestructiveTextColorWithId_(ASActionSheetPlugin *self, id destructiveTextColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetDestructiveBackgroundColorWithId_(ASActionSheetPlugin *self, id bgColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetDestructiveHighlightColorWithId_(ASActionSheetPlugin *self, id bgColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetDestructiveTextSizeWithFloat_(ASActionSheetPlugin *self, float value);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetDestructiveFontFamilyWithNSString_withFloat_(ASActionSheetPlugin *self, NSString *fontName, float textSize);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetOtherTextColorWithId_(ASActionSheetPlugin *self, id otherTextColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetOtherBackgroundColorWithId_(ASActionSheetPlugin *self, id bgColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetOtherHighlightColorWithId_(ASActionSheetPlugin *self, id bgColor);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetOtherTextSizeWithFloat_(ASActionSheetPlugin *self, float value);

__attribute__((unused)) static void ASActionSheetPlugin_nativeSetOtherFontFamilyWithNSString_withFloat_(ASActionSheetPlugin *self, NSString *fontName, float textSize);

@implementation ASActionSheetPlugin

@synthesize uiActionSheet = uiActionSheet_;

+ (void)initPlugin {
  ASActionSheetPlugin_initPlugin();
}

- (instancetype)initWithNSString:(NSString *)parentFragmentId
                          withId:(id)uiActionSheet {
  ASActionSheetPlugin_initWithNSString_withId_(self, parentFragmentId, uiActionSheet);
  return self;
}

- (void)setTitleTextColorWithNSString:(NSString *)titleTextColor {
  if (titleTextColor != nil && ![titleTextColor isEmpty]) {
    id titleTextColorObj = ASActionSheetPlugin_getTextColorWithNSString_(self, titleTextColor);
    ASActionSheetPlugin_nativeSetTitleTextColorWithId_(self, titleTextColorObj);
  }
}

- (void)setTitleBackgroundColorWithNSString:(NSString *)titleBackgroundColor {
  if (titleBackgroundColor != nil && ![titleBackgroundColor isEmpty]) {
    id titleBgObj = ASActionSheetPlugin_getTextColorWithNSString_(self, titleBackgroundColor);
    ASActionSheetPlugin_nativeSetTitleBackgroundColorWithId_(self, titleBgObj);
  }
}

- (void)setTitleFontFamilyWithNSString:(NSString *)titleFontFamily
                               withInt:(int32_t)titleTextSize {
  if (titleFontFamily != nil && ![titleFontFamily isEmpty]) {
    ASFontDescriptor *fontDescriptor = ASActionSheetPlugin_getFontFamilyDescriptorWithNSString_(self, titleFontFamily);
    float textSize = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(ASActionSheetPlugin_getTextSizeWithInt_(self, titleTextSize), [JavaLangFloat class]))) floatValue];
    ASActionSheetPlugin_nativeSetTitleFontFamilyWithNSString_withFloat_(self, [((ASFontDescriptor *) nil_chk(fontDescriptor)) getName], textSize);
  }
}

- (void)setTitleTextSizeWithInt:(int32_t)titleTextSize {
  float textSize = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(ASActionSheetPlugin_getTextSizeWithInt_(self, titleTextSize), [JavaLangFloat class]))) floatValue];
  ASActionSheetPlugin_nativeSetTitleTextSizeWithFloat_(self, textSize);
}

- (void)nativeSetTitleTextColorWithId:(id)titleTextColor {
  ASActionSheetPlugin_nativeSetTitleTextColorWithId_(self, titleTextColor);
}

- (void)nativeSetTitleBackgroundColorWithId:(id)bgColor {
  ASActionSheetPlugin_nativeSetTitleBackgroundColorWithId_(self, bgColor);
}

- (void)nativeSetTitleTextSizeWithFloat:(float)value {
  ASActionSheetPlugin_nativeSetTitleTextSizeWithFloat_(self, value);
}

- (void)nativeSetTitleFontFamilyWithNSString:(NSString *)fontName
                                   withFloat:(float)textSize {
  ASActionSheetPlugin_nativeSetTitleFontFamilyWithNSString_withFloat_(self, fontName, textSize);
}

- (ASFontDescriptor *)getFontFamilyDescriptorWithNSString:(NSString *)fontName {
  return ASActionSheetPlugin_getFontFamilyDescriptorWithNSString_(self, fontName);
}

- (id)getTextSizeWithInt:(int32_t)textSize {
  return ASActionSheetPlugin_getTextSizeWithInt_(self, textSize);
}

- (id)getTextColorWithNSString:(NSString *)color {
  return ASActionSheetPlugin_getTextColorWithNSString_(self, color);
}

- (id<ASIFragment>)getMyParentFragmentWithNSString:(NSString *)fragmentId {
  return [((ASFragmentRegistry *) nil_chk(ASFragmentRegistry_getInstance())) findWithNSString:fragmentId];
}

- (void)setCancelTextColorWithNSString:(NSString *)cancelTextColor {
  if (cancelTextColor != nil && ![cancelTextColor isEmpty]) {
    id cancelTextColorObj = ASActionSheetPlugin_getTextColorWithNSString_(self, cancelTextColor);
    ASActionSheetPlugin_nativeSetCancelTextColorWithId_(self, cancelTextColorObj);
  }
}

- (void)setCancelBackgroundColorWithNSString:(NSString *)cancelBackgroundColor {
  if (cancelBackgroundColor != nil && ![cancelBackgroundColor isEmpty]) {
    id cancelBgObj = ASActionSheetPlugin_getTextColorWithNSString_(self, cancelBackgroundColor);
    ASActionSheetPlugin_nativeSetCancelBackgroundColorWithId_(self, cancelBgObj);
  }
}

- (void)setCancelHighlightColorWithNSString:(NSString *)cancelBackgroundColor {
  if (cancelBackgroundColor != nil && ![cancelBackgroundColor isEmpty]) {
    id cancelBgObj = ASActionSheetPlugin_getTextColorWithNSString_(self, cancelBackgroundColor);
    ASActionSheetPlugin_nativeSetCancelHighlightColorWithId_(self, cancelBgObj);
  }
}

- (void)setCancelFontFamilyWithNSString:(NSString *)cancelFontFamily
                                withInt:(int32_t)cancelTextSize {
  if (cancelFontFamily != nil && ![cancelFontFamily isEmpty]) {
    ASFontDescriptor *fontDescriptor = ASActionSheetPlugin_getFontFamilyDescriptorWithNSString_(self, cancelFontFamily);
    float textSize = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(ASActionSheetPlugin_getTextSizeWithInt_(self, cancelTextSize), [JavaLangFloat class]))) floatValue];
    ASActionSheetPlugin_nativeSetCancelFontFamilyWithNSString_withFloat_(self, [((ASFontDescriptor *) nil_chk(fontDescriptor)) getName], textSize);
  }
}

- (void)setCancelTextSizeWithInt:(int32_t)cancelTextSize {
  float textSize = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(ASActionSheetPlugin_getTextSizeWithInt_(self, cancelTextSize), [JavaLangFloat class]))) floatValue];
  ASActionSheetPlugin_nativeSetCancelTextSizeWithFloat_(self, textSize);
}

- (void)nativeSetCancelTextColorWithId:(id)cancelTextColor {
  ASActionSheetPlugin_nativeSetCancelTextColorWithId_(self, cancelTextColor);
}

- (void)nativeSetCancelBackgroundColorWithId:(id)bgColor {
  ASActionSheetPlugin_nativeSetCancelBackgroundColorWithId_(self, bgColor);
}

- (void)nativeSetCancelHighlightColorWithId:(id)bgColor {
  ASActionSheetPlugin_nativeSetCancelHighlightColorWithId_(self, bgColor);
}

- (void)nativeSetCancelTextSizeWithFloat:(float)value {
  ASActionSheetPlugin_nativeSetCancelTextSizeWithFloat_(self, value);
}

- (void)nativeSetCancelFontFamilyWithNSString:(NSString *)fontName
                                    withFloat:(float)textSize {
  ASActionSheetPlugin_nativeSetCancelFontFamilyWithNSString_withFloat_(self, fontName, textSize);
}

- (void)setDestructiveTextColorWithNSString:(NSString *)destructiveTextColor {
  if (destructiveTextColor != nil && ![destructiveTextColor isEmpty]) {
    id destructiveTextColorObj = ASActionSheetPlugin_getTextColorWithNSString_(self, destructiveTextColor);
    ASActionSheetPlugin_nativeSetDestructiveTextColorWithId_(self, destructiveTextColorObj);
  }
}

- (void)setDestructiveBackgroundColorWithNSString:(NSString *)destructiveBackgroundColor {
  if (destructiveBackgroundColor != nil && ![destructiveBackgroundColor isEmpty]) {
    id destructiveBgObj = ASActionSheetPlugin_getTextColorWithNSString_(self, destructiveBackgroundColor);
    ASActionSheetPlugin_nativeSetDestructiveBackgroundColorWithId_(self, destructiveBgObj);
  }
}

- (void)setDestructiveHighlightColorWithNSString:(NSString *)destructiveBackgroundColor {
  if (destructiveBackgroundColor != nil && ![destructiveBackgroundColor isEmpty]) {
    id destructiveBgObj = ASActionSheetPlugin_getTextColorWithNSString_(self, destructiveBackgroundColor);
    ASActionSheetPlugin_nativeSetDestructiveHighlightColorWithId_(self, destructiveBgObj);
  }
}

- (void)setDestructiveFontFamilyWithNSString:(NSString *)destructiveFontFamily
                                     withInt:(int32_t)destructiveTextSize {
  if (destructiveFontFamily != nil && ![destructiveFontFamily isEmpty]) {
    ASFontDescriptor *fontDescriptor = ASActionSheetPlugin_getFontFamilyDescriptorWithNSString_(self, destructiveFontFamily);
    float textSize = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(ASActionSheetPlugin_getTextSizeWithInt_(self, destructiveTextSize), [JavaLangFloat class]))) floatValue];
    ASActionSheetPlugin_nativeSetDestructiveFontFamilyWithNSString_withFloat_(self, [((ASFontDescriptor *) nil_chk(fontDescriptor)) getName], textSize);
  }
}

- (void)setDestructiveTextSizeWithInt:(int32_t)destructiveTextSize {
  float textSize = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(ASActionSheetPlugin_getTextSizeWithInt_(self, destructiveTextSize), [JavaLangFloat class]))) floatValue];
  ASActionSheetPlugin_nativeSetDestructiveTextSizeWithFloat_(self, textSize);
}

- (void)nativeSetDestructiveTextColorWithId:(id)destructiveTextColor {
  ASActionSheetPlugin_nativeSetDestructiveTextColorWithId_(self, destructiveTextColor);
}

- (void)nativeSetDestructiveBackgroundColorWithId:(id)bgColor {
  ASActionSheetPlugin_nativeSetDestructiveBackgroundColorWithId_(self, bgColor);
}

- (void)nativeSetDestructiveHighlightColorWithId:(id)bgColor {
  ASActionSheetPlugin_nativeSetDestructiveHighlightColorWithId_(self, bgColor);
}

- (void)nativeSetDestructiveTextSizeWithFloat:(float)value {
  ASActionSheetPlugin_nativeSetDestructiveTextSizeWithFloat_(self, value);
}

- (void)nativeSetDestructiveFontFamilyWithNSString:(NSString *)fontName
                                         withFloat:(float)textSize {
  ASActionSheetPlugin_nativeSetDestructiveFontFamilyWithNSString_withFloat_(self, fontName, textSize);
}

- (void)setOtherTextColorWithNSString:(NSString *)otherTextColor {
  if (otherTextColor != nil && ![otherTextColor isEmpty]) {
    id otherTextColorObj = ASActionSheetPlugin_getTextColorWithNSString_(self, otherTextColor);
    ASActionSheetPlugin_nativeSetOtherTextColorWithId_(self, otherTextColorObj);
  }
}

- (void)setOtherBackgroundColorWithNSString:(NSString *)otherBackgroundColor {
  if (otherBackgroundColor != nil && ![otherBackgroundColor isEmpty]) {
    id otherBgObj = ASActionSheetPlugin_getTextColorWithNSString_(self, otherBackgroundColor);
    ASActionSheetPlugin_nativeSetOtherBackgroundColorWithId_(self, otherBgObj);
  }
}

- (void)setOtherHighlightColorWithNSString:(NSString *)otherBackgroundColor {
  if (otherBackgroundColor != nil && ![otherBackgroundColor isEmpty]) {
    id otherBgObj = ASActionSheetPlugin_getTextColorWithNSString_(self, otherBackgroundColor);
    ASActionSheetPlugin_nativeSetOtherHighlightColorWithId_(self, otherBgObj);
  }
}

- (void)setOtherFontFamilyWithNSString:(NSString *)otherFontFamily
                               withInt:(int32_t)otherTextSize {
  if (otherFontFamily != nil && ![otherFontFamily isEmpty]) {
    ASFontDescriptor *fontDescriptor = ASActionSheetPlugin_getFontFamilyDescriptorWithNSString_(self, otherFontFamily);
    float textSize = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(ASActionSheetPlugin_getTextSizeWithInt_(self, otherTextSize), [JavaLangFloat class]))) floatValue];
    ASActionSheetPlugin_nativeSetOtherFontFamilyWithNSString_withFloat_(self, [((ASFontDescriptor *) nil_chk(fontDescriptor)) getName], textSize);
  }
}

- (void)setOtherTextSizeWithInt:(int32_t)otherTextSize {
  float textSize = [((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(ASActionSheetPlugin_getTextSizeWithInt_(self, otherTextSize), [JavaLangFloat class]))) floatValue];
  ASActionSheetPlugin_nativeSetOtherTextSizeWithFloat_(self, textSize);
}

- (void)nativeSetOtherTextColorWithId:(id)otherTextColor {
  ASActionSheetPlugin_nativeSetOtherTextColorWithId_(self, otherTextColor);
}

- (void)nativeSetOtherBackgroundColorWithId:(id)bgColor {
  ASActionSheetPlugin_nativeSetOtherBackgroundColorWithId_(self, bgColor);
}

- (void)nativeSetOtherHighlightColorWithId:(id)bgColor {
  ASActionSheetPlugin_nativeSetOtherHighlightColorWithId_(self, bgColor);
}

- (void)nativeSetOtherTextSizeWithFloat:(float)value {
  ASActionSheetPlugin_nativeSetOtherTextSizeWithFloat_(self, value);
}

- (void)nativeSetOtherFontFamilyWithNSString:(NSString *)fontName
                                   withFloat:(float)textSize {
  ASActionSheetPlugin_nativeSetOtherFontFamilyWithNSString_withFloat_(self, fontName, textSize);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 10, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 13, 14, -1, -1, -1, -1 },
    { NULL, "LASFontDescriptor;", 0x2, 15, 2, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, 16, 7, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x2, 17, 2, -1, -1, -1, -1 },
    { NULL, "LASIFragment;", 0x1, 18, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 19, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 21, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 23, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 24, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 25, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 26, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 27, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 28, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 30, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 32, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 34, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 35, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 36, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 37, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 38, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 39, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 40, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 41, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 42, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 43, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 44, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 45, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 46, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 47, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x102, 48, 14, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initPlugin);
  methods[1].selector = @selector(initWithNSString:withId:);
  methods[2].selector = @selector(setTitleTextColorWithNSString:);
  methods[3].selector = @selector(setTitleBackgroundColorWithNSString:);
  methods[4].selector = @selector(setTitleFontFamilyWithNSString:withInt:);
  methods[5].selector = @selector(setTitleTextSizeWithInt:);
  methods[6].selector = @selector(nativeSetTitleTextColorWithId:);
  methods[7].selector = @selector(nativeSetTitleBackgroundColorWithId:);
  methods[8].selector = @selector(nativeSetTitleTextSizeWithFloat:);
  methods[9].selector = @selector(nativeSetTitleFontFamilyWithNSString:withFloat:);
  methods[10].selector = @selector(getFontFamilyDescriptorWithNSString:);
  methods[11].selector = @selector(getTextSizeWithInt:);
  methods[12].selector = @selector(getTextColorWithNSString:);
  methods[13].selector = @selector(getMyParentFragmentWithNSString:);
  methods[14].selector = @selector(setCancelTextColorWithNSString:);
  methods[15].selector = @selector(setCancelBackgroundColorWithNSString:);
  methods[16].selector = @selector(setCancelHighlightColorWithNSString:);
  methods[17].selector = @selector(setCancelFontFamilyWithNSString:withInt:);
  methods[18].selector = @selector(setCancelTextSizeWithInt:);
  methods[19].selector = @selector(nativeSetCancelTextColorWithId:);
  methods[20].selector = @selector(nativeSetCancelBackgroundColorWithId:);
  methods[21].selector = @selector(nativeSetCancelHighlightColorWithId:);
  methods[22].selector = @selector(nativeSetCancelTextSizeWithFloat:);
  methods[23].selector = @selector(nativeSetCancelFontFamilyWithNSString:withFloat:);
  methods[24].selector = @selector(setDestructiveTextColorWithNSString:);
  methods[25].selector = @selector(setDestructiveBackgroundColorWithNSString:);
  methods[26].selector = @selector(setDestructiveHighlightColorWithNSString:);
  methods[27].selector = @selector(setDestructiveFontFamilyWithNSString:withInt:);
  methods[28].selector = @selector(setDestructiveTextSizeWithInt:);
  methods[29].selector = @selector(nativeSetDestructiveTextColorWithId:);
  methods[30].selector = @selector(nativeSetDestructiveBackgroundColorWithId:);
  methods[31].selector = @selector(nativeSetDestructiveHighlightColorWithId:);
  methods[32].selector = @selector(nativeSetDestructiveTextSizeWithFloat:);
  methods[33].selector = @selector(nativeSetDestructiveFontFamilyWithNSString:withFloat:);
  methods[34].selector = @selector(setOtherTextColorWithNSString:);
  methods[35].selector = @selector(setOtherBackgroundColorWithNSString:);
  methods[36].selector = @selector(setOtherHighlightColorWithNSString:);
  methods[37].selector = @selector(setOtherFontFamilyWithNSString:withInt:);
  methods[38].selector = @selector(setOtherTextSizeWithInt:);
  methods[39].selector = @selector(nativeSetOtherTextColorWithId:);
  methods[40].selector = @selector(nativeSetOtherBackgroundColorWithId:);
  methods[41].selector = @selector(nativeSetOtherHighlightColorWithId:);
  methods[42].selector = @selector(nativeSetOtherTextSizeWithFloat:);
  methods[43].selector = @selector(nativeSetOtherFontFamilyWithNSString:withFloat:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "parentFragmentId_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "uiActionSheet_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;LNSObject;", "setTitleTextColor", "LNSString;", "setTitleBackgroundColor", "setTitleFontFamily", "LNSString;I", "setTitleTextSize", "I", "nativeSetTitleTextColor", "LNSObject;", "nativeSetTitleBackgroundColor", "nativeSetTitleTextSize", "F", "nativeSetTitleFontFamily", "LNSString;F", "getFontFamilyDescriptor", "getTextSize", "getTextColor", "getMyParentFragment", "setCancelTextColor", "setCancelBackgroundColor", "setCancelHighlightColor", "setCancelFontFamily", "setCancelTextSize", "nativeSetCancelTextColor", "nativeSetCancelBackgroundColor", "nativeSetCancelHighlightColor", "nativeSetCancelTextSize", "nativeSetCancelFontFamily", "setDestructiveTextColor", "setDestructiveBackgroundColor", "setDestructiveHighlightColor", "setDestructiveFontFamily", "setDestructiveTextSize", "nativeSetDestructiveTextColor", "nativeSetDestructiveBackgroundColor", "nativeSetDestructiveHighlightColor", "nativeSetDestructiveTextSize", "nativeSetDestructiveFontFamily", "setOtherTextColor", "setOtherBackgroundColor", "setOtherHighlightColor", "setOtherFontFamily", "setOtherTextSize", "nativeSetOtherTextColor", "nativeSetOtherBackgroundColor", "nativeSetOtherHighlightColor", "nativeSetOtherTextSize", "nativeSetOtherFontFamily" };
  static const J2ObjcClassInfo _ASActionSheetPlugin = { "ActionSheetPlugin", "com.ashera.actionsheet", ptrTable, methods, fields, 7, 0x1, 44, 2, -1, -1, -1, -1, -1 };
  return &_ASActionSheetPlugin;
}

@end

void ASActionSheetPlugin_initPlugin() {
  ASActionSheetPlugin_initialize();
}

void ASActionSheetPlugin_initWithNSString_withId_(ASActionSheetPlugin *self, NSString *parentFragmentId, id uiActionSheet) {
  NSObject_init(self);
  self->parentFragmentId_ = parentFragmentId;
  self->uiActionSheet_ = uiActionSheet;
}

ASActionSheetPlugin *new_ASActionSheetPlugin_initWithNSString_withId_(NSString *parentFragmentId, id uiActionSheet) {
  J2OBJC_NEW_IMPL(ASActionSheetPlugin, initWithNSString_withId_, parentFragmentId, uiActionSheet)
}

ASActionSheetPlugin *create_ASActionSheetPlugin_initWithNSString_withId_(NSString *parentFragmentId, id uiActionSheet) {
  J2OBJC_CREATE_IMPL(ASActionSheetPlugin, initWithNSString_withId_, parentFragmentId, uiActionSheet)
}

void ASActionSheetPlugin_nativeSetTitleTextColorWithId_(ASActionSheetPlugin *self, id titleTextColor) {
  [((IBActionSheet*)self.uiActionSheet) setTitleTextColor: (UIColor*) titleTextColor];
}

void ASActionSheetPlugin_nativeSetTitleBackgroundColorWithId_(ASActionSheetPlugin *self, id bgColor) {
  [((IBActionSheet*)self.uiActionSheet) setTitleBackgroundColor: (UIColor*) bgColor];
}

void ASActionSheetPlugin_nativeSetTitleTextSizeWithFloat_(ASActionSheetPlugin *self, float value) {
  IBActionSheet* uiActionSheet = ((IBActionSheet*)self.uiActionSheet);
  [uiActionSheet setFont: [uiActionSheet.titleView.titleLabel.font fontWithSize: value]];
}

void ASActionSheetPlugin_nativeSetTitleFontFamilyWithNSString_withFloat_(ASActionSheetPlugin *self, NSString *fontName, float textSize) {
  [((IBActionSheet*)self.uiActionSheet) setTitleFont: [UIFont fontWithName:fontName size:textSize]];
}

ASFontDescriptor *ASActionSheetPlugin_getFontFamilyDescriptorWithNSString_(ASActionSheetPlugin *self, NSString *fontName) {
  id<JavaUtilMap> fontDescriptors = (id<JavaUtilMap>) cast_check([((id<ASIConverter>) nil_chk(ASPluginInvoker_getConverterWithNSString_(@"font"))) convertFromWithId:fontName withJavaUtilMap:new_JavaUtilHashMap_init() withASIFragment:[self getMyParentFragmentWithNSString:self->parentFragmentId_]], JavaUtilMap_class_());
  NSString *weight = @"400";
  NSString *fontStyle = @"normal";
  ASFontDescriptor *fontDescriptor = [((id<JavaUtilMap>) nil_chk(fontDescriptors)) getWithId:JreStrcat("$C$", fontStyle, '_', weight)];
  return fontDescriptor;
}

id ASActionSheetPlugin_getTextSizeWithInt_(ASActionSheetPlugin *self, int32_t textSize) {
  id objValue = [((id<ASIConverter>) nil_chk(ASPluginInvoker_getConverterWithNSString_(@"dimensionsp"))) convertFromWithId:JreStrcat("I$", textSize, @"sp") withJavaUtilMap:new_JavaUtilHashMap_init() withASIFragment:[self getMyParentFragmentWithNSString:self->parentFragmentId_]];
  return objValue;
}

id ASActionSheetPlugin_getTextColorWithNSString_(ASActionSheetPlugin *self, NSString *color) {
  id objValue = [((id<ASIConverter>) nil_chk(ASPluginInvoker_getConverterWithNSString_(@"color"))) convertFromWithId:color withJavaUtilMap:new_JavaUtilHashMap_init() withASIFragment:[self getMyParentFragmentWithNSString:self->parentFragmentId_]];
  return objValue;
}

void ASActionSheetPlugin_nativeSetCancelTextColorWithId_(ASActionSheetPlugin *self, id cancelTextColor) {
  [((IBActionSheet*)self.uiActionSheet) setCancelButtonTextColor: (UIColor*) cancelTextColor];
}

void ASActionSheetPlugin_nativeSetCancelBackgroundColorWithId_(ASActionSheetPlugin *self, id bgColor) {
  [((IBActionSheet*)self.uiActionSheet) setCancelButtonBackgroundColor: (UIColor*) bgColor];
}

void ASActionSheetPlugin_nativeSetCancelHighlightColorWithId_(ASActionSheetPlugin *self, id bgColor) {
  [((IBActionSheet*)self.uiActionSheet) setCancelButtonHighlightColor: (UIColor*) bgColor];
}

void ASActionSheetPlugin_nativeSetCancelTextSizeWithFloat_(ASActionSheetPlugin *self, float value) {
  IBActionSheet* uiActionSheet = ((IBActionSheet*)self.uiActionSheet);
  UIButton* btn = [uiActionSheet getCancelButton];
  if (btn != nil) {
    [uiActionSheet setFont: [btn.font fontWithSize: value]];
  }
}

void ASActionSheetPlugin_nativeSetCancelFontFamilyWithNSString_withFloat_(ASActionSheetPlugin *self, NSString *fontName, float textSize) {
  [((IBActionSheet*)self.uiActionSheet) setCancelButtonFont: [UIFont fontWithName:fontName size:textSize]];
}

void ASActionSheetPlugin_nativeSetDestructiveTextColorWithId_(ASActionSheetPlugin *self, id destructiveTextColor) {
  [((IBActionSheet*)self.uiActionSheet) setDestructiveButtonTextColor: (UIColor*) destructiveTextColor];
}

void ASActionSheetPlugin_nativeSetDestructiveBackgroundColorWithId_(ASActionSheetPlugin *self, id bgColor) {
  [((IBActionSheet*)self.uiActionSheet) setDestructiveButtonBackgroundColor: (UIColor*) bgColor];
}

void ASActionSheetPlugin_nativeSetDestructiveHighlightColorWithId_(ASActionSheetPlugin *self, id bgColor) {
  [((IBActionSheet*)self.uiActionSheet) setDestructiveButtonHighlightColor: (UIColor*) bgColor];
}

void ASActionSheetPlugin_nativeSetDestructiveTextSizeWithFloat_(ASActionSheetPlugin *self, float value) {
  IBActionSheet* uiActionSheet = ((IBActionSheet*)self.uiActionSheet);
  UIButton* btn = [uiActionSheet getDestructiveButton];
  if (btn != nil) {
    [uiActionSheet setFont: [btn.font fontWithSize: value]];
  }
}

void ASActionSheetPlugin_nativeSetDestructiveFontFamilyWithNSString_withFloat_(ASActionSheetPlugin *self, NSString *fontName, float textSize) {
  [((IBActionSheet*)self.uiActionSheet) setDestructiveButtonFont: [UIFont fontWithName:fontName size:textSize]];
}

void ASActionSheetPlugin_nativeSetOtherTextColorWithId_(ASActionSheetPlugin *self, id otherTextColor) {
  [((IBActionSheet*)self.uiActionSheet) setOtherButtonTextColor: (UIColor*) otherTextColor];
}

void ASActionSheetPlugin_nativeSetOtherBackgroundColorWithId_(ASActionSheetPlugin *self, id bgColor) {
  [((IBActionSheet*)self.uiActionSheet) setOtherButtonBackgroundColor: (UIColor*) bgColor];
}

void ASActionSheetPlugin_nativeSetOtherHighlightColorWithId_(ASActionSheetPlugin *self, id bgColor) {
  [((IBActionSheet*)self.uiActionSheet) setOtherButtonHighlightColor: (UIColor*) bgColor];
}

void ASActionSheetPlugin_nativeSetOtherTextSizeWithFloat_(ASActionSheetPlugin *self, float value) {
  IBActionSheet* uiActionSheet = ((IBActionSheet*)self.uiActionSheet);
  [((IBActionSheet*)self.uiActionSheet) setOtherButtonTextSize: value];
}

void ASActionSheetPlugin_nativeSetOtherFontFamilyWithNSString_withFloat_(ASActionSheetPlugin *self, NSString *fontName, float textSize) {
  [((IBActionSheet*)self.uiActionSheet) setOtherButtonFont: [UIFont fontWithName:fontName size:textSize]];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASActionSheetPlugin)

J2OBJC_NAME_MAPPING(ASActionSheetPlugin, "com.ashera.actionsheet", "AS")
