//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSActionSheetPlugin\src\main\java\com\ashera\actionsheet\ActionSheetPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ActionSheetPlugin")
#ifdef RESTRICT_ActionSheetPlugin
#define INCLUDE_ALL_ActionSheetPlugin 0
#else
#define INCLUDE_ALL_ActionSheetPlugin 1
#endif
#undef RESTRICT_ActionSheetPlugin

#if !defined (ASActionSheetPlugin_) && (INCLUDE_ALL_ActionSheetPlugin || defined(INCLUDE_ASActionSheetPlugin))
#define ASActionSheetPlugin_

@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;

@interface ASActionSheetPlugin : NSObject
@property id uiActionSheet;

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)parentFragmentId
                          withId:(id)uiActionSheet;

- (id<ASIFragment>)getMyParentFragmentWithNSString:(NSString *)fragmentId;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

- (void)setCancelBackgroundColorWithNSString:(NSString *)cancelBackgroundColor;

- (void)setCancelFontFamilyWithNSString:(NSString *)cancelFontFamily
                                withInt:(int32_t)cancelTextSize;

- (void)setCancelHighlightColorWithNSString:(NSString *)cancelBackgroundColor;

- (void)setCancelTextColorWithNSString:(NSString *)cancelTextColor;

- (void)setCancelTextSizeWithInt:(int32_t)cancelTextSize;

- (void)setDestructiveBackgroundColorWithNSString:(NSString *)destructiveBackgroundColor;

- (void)setDestructiveFontFamilyWithNSString:(NSString *)destructiveFontFamily
                                     withInt:(int32_t)destructiveTextSize;

- (void)setDestructiveHighlightColorWithNSString:(NSString *)destructiveBackgroundColor;

- (void)setDestructiveTextColorWithNSString:(NSString *)destructiveTextColor;

- (void)setDestructiveTextSizeWithInt:(int32_t)destructiveTextSize;

- (void)setOtherBackgroundColorWithNSString:(NSString *)otherBackgroundColor;

- (void)setOtherFontFamilyWithNSString:(NSString *)otherFontFamily
                               withInt:(int32_t)otherTextSize;

- (void)setOtherHighlightColorWithNSString:(NSString *)otherBackgroundColor;

- (void)setOtherTextColorWithNSString:(NSString *)otherTextColor;

- (void)setOtherTextSizeWithInt:(int32_t)otherTextSize;

- (void)setTitleBackgroundColorWithNSString:(NSString *)titleBackgroundColor;

- (void)setTitleFontFamilyWithNSString:(NSString *)titleFontFamily
                               withInt:(int32_t)titleTextSize;

- (void)setTitleTextColorWithNSString:(NSString *)titleTextColor;

- (void)setTitleTextSizeWithInt:(int32_t)titleTextSize;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASActionSheetPlugin)

FOUNDATION_EXPORT void ASActionSheetPlugin_initPlugin(void);

FOUNDATION_EXPORT void ASActionSheetPlugin_initWithNSString_withId_(ASActionSheetPlugin *self, NSString *parentFragmentId, id uiActionSheet);

FOUNDATION_EXPORT ASActionSheetPlugin *new_ASActionSheetPlugin_initWithNSString_withId_(NSString *parentFragmentId, id uiActionSheet) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASActionSheetPlugin *create_ASActionSheetPlugin_initWithNSString_withId_(NSString *parentFragmentId, id uiActionSheet);

J2OBJC_TYPE_LITERAL_HEADER(ASActionSheetPlugin)

@compatibility_alias ComAsheraActionsheetActionSheetPlugin ASActionSheetPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_ActionSheetPlugin")
